import { IModulo } from './modulo';

// export interface ITipoTramite {
//   id:number,
//   nombre: string;
//   descripcion: string;
//   link?: string;
//   linkName?: string;
//   link1?: string;
//   link1Name?: string;
//   modulos?: IModulo[]
// }

// Generated by https://quicktype.io

export interface ITipoTramite {
  id: number;
  pk: string;
  nombre: string;
  descripcion: string;
  acto?: Acto[];
  registro?: Acto[];
  modulos?: Acto[];
}

export interface Acto {
  id: number;
  pk: string;
  nombre: string;
  abreviatura: string;
  descripcion: string;
}
